spring:
  config:
    activate:
      on-profile: dev
  jpa:
    show-sql: false
logging:
  level:
    root: INFO
    com.ticketing.booking: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: ERROR
    org.apache.kafka.clients.NetworkClient: ERROR
