version: "3.8"

services:
  # Master PostgreSQL instance for Auth Service
  postgres-master:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_system_auth
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "55432:5432"
    volumes:
      - postgres_master_data:/var/lib/postgresql/data
      - ./postgres-master-init:/docker-entrypoint-initdb.d
    networks:
      - booking-net
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=3
      -c max_replication_slots=3
      -c hot_standby=on
      -c archive_mode=on
      -c archive_command='test ! -f /var/lib/postgresql/backup_in_progress && (test ! -f /var/lib/postgresql/archive/%f || cp %p /var/lib/postgresql/archive/%f)'
      -c archive_timeout=10
      -c synchronous_commit=on
      -c wal_sync_method=fsync
      -c checkpoint_timeout=5min
      -c max_wal_size=1GB
      -c min_wal_size=80MB

  # Slave PostgreSQL instance 1 for Auth Service
  postgres-slave1:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_system_auth
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      POSTGRES_MASTER_HOST: postgres-master
      POSTGRES_MASTER_PORT: 5432
      POSTGRES_MASTER_USER: booking_user
      POSTGRES_MASTER_PASSWORD: booking_pass
    ports:
      - "55433:5432"
    volumes:
      - postgres_slave1_data:/var/lib/postgresql/data
      - ./postgres-slave-init/01-init-slave.sh:/docker-entrypoint-initdb.d/01-init-slave.sh
    networks:
      - booking-net
    depends_on:
      - postgres-master
    command: >
      postgres
      -c hot_standby=on
      -c primary_conninfo='host=postgres-master port=5432 user=replicator password=replicator_pass application_name=slave1'
      -c restore_command='cp /var/lib/postgresql/archive/%f %p'
      -c recovery_target_timeline='latest'
      -c max_standby_archive_delay=30s
      -c max_standby_streaming_delay=30s
      -c wal_receiver_status_interval=10s
      -c hot_standby_feedback=on

  # Slave PostgreSQL instance 2 for Auth Service (optional)
  postgres-slave2:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_system_auth
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      POSTGRES_MASTER_HOST: postgres-master
      POSTGRES_MASTER_PORT: 5432
      POSTGRES_MASTER_USER: booking_user
      POSTGRES_MASTER_PASSWORD: booking_pass
    ports:
      - "55434:5432"
    volumes:
      - postgres_slave2_data:/var/lib/postgresql/data
      - ./postgres-slave-init/01-init-slave2.sh:/docker-entrypoint-initdb.d/01-init-slave2.sh
    networks:
      - booking-net
    depends_on:
      - postgres-master
    command: >
      postgres
      -c hot_standby=on
      -c primary_conninfo='host=postgres-master port=5432 user=replicator password=replicator_pass application_name=slave2'
      -c restore_command='cp /var/lib/postgresql/archive/%f %p'
      -c recovery_target_timeline='latest'
      -c max_standby_archive_delay=30s
      -c max_standby_streaming_delay=30s
      -c wal_receiver_status_interval=10s
      -c hot_standby_feedback=on

  # Master PostgreSQL instance for Main Application (booking_system)
  postgres-main-master:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_system
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    ports:
      - "55435:5432"
    volumes:
      - postgres_main_master_data:/var/lib/postgresql/data
      - ./postgres-main-master-init:/docker-entrypoint-initdb.d
    networks:
      - booking-net
    command: >
      postgres
      -c wal_level=replica
      -c max_wal_senders=3
      -c max_replication_slots=3
      -c hot_standby=on
      -c archive_mode=on
      -c archive_command='test ! -f /var/lib/postgresql/backup_in_progress && (test ! -f /var/lib/postgresql/archive/%f || cp %p /var/lib/postgresql/archive/%f)'
      -c archive_timeout=10
      -c synchronous_commit=on
      -c wal_sync_method=fsync
      -c checkpoint_timeout=5min
      -c max_wal_size=1GB
      -c min_wal_size=80MB

  # Slave PostgreSQL instance 1 for Main Application (booking_system)
  postgres-main-slave1:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_system
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      POSTGRES_MASTER_HOST: postgres-main-master
      POSTGRES_MASTER_PORT: 5432
      POSTGRES_MASTER_USER: booking_user
      POSTGRES_MASTER_PASSWORD: booking_pass
    ports:
      - "55436:5432"
    volumes:
      - postgres_main_slave1_data:/var/lib/postgresql/data
      - ./postgres-main-slave-init/01-init-slave.sh:/docker-entrypoint-initdb.d/01-init-slave.sh
    networks:
      - booking-net
    depends_on:
      - postgres-main-master
    command: >
      postgres
      -c hot_standby=on
      -c primary_conninfo='host=postgres-main-master port=5432 user=replicator password=replicator_pass application_name=main-slave1'
      -c restore_command='cp /var/lib/postgresql/archive/%f %p'
      -c recovery_target_timeline='latest'
      -c max_standby_archive_delay=30s
      -c max_standby_streaming_delay=30s
      -c wal_receiver_status_interval=10s
      -c hot_standby_feedback=on

  # Slave PostgreSQL instance 2 for Main Application (booking_system) (optional)
  postgres-main-slave2:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_system
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      POSTGRES_MASTER_HOST: postgres-main-master
      POSTGRES_MASTER_PORT: 5432
      POSTGRES_MASTER_USER: booking_user
      POSTGRES_MASTER_PASSWORD: booking_pass
    ports:
      - "55437:5432"
    volumes:
      - postgres_main_slave2_data:/var/lib/postgresql/data
      - ./postgres-main-slave-init/01-init-slave2.sh:/docker-entrypoint-initdb.d/01-init-slave2.sh
    networks:
      - booking-net
    depends_on:
      - postgres-main-master
    command: >
      postgres
      -c hot_standby=on
      -c primary_conninfo='host=postgres-main-master port=5432 user=replicator password=replicator_pass application_name=main-slave2'
      -c restore_command='cp /var/lib/postgresql/archive/%f %p'
      -c recovery_target_timeline='latest'
      -c max_standby_archive_delay=30s
      -c max_standby_streaming_delay=30s
      -c wal_receiver_status_interval=10s
      -c hot_standby_feedback=on

  redis:
    image: redis:7-alpine
    ports:
      - "56379:6379"
    volumes:
      - redis_data:/data
    networks:
      - booking-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "52181:2181"
    networks:
      - booking-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "59092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - booking-net

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "59090:9090"
    volumes:
      - ./prometheus.dev.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.dev.yml:/etc/prometheus/alert_rules.dev.yml
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--storage.tsdb.retention.time=15d"
      - "--storage.tsdb.retention.size=512MB"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - booking-net
    restart: unless-stopped

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "59093:9093"
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager_data:/alertmanager
    command:
      - "--config.file=/etc/alertmanager/alertmanager.yml"
      - "--storage.path=/alertmanager"
    networks:
      - booking-net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    ports:
      - "53001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_ADMIN_USER: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - booking-net
    restart: unless-stopped
    depends_on:
      - prometheus

  node-exporter:
    image: prom/node-exporter:latest
    ports:
      - "59100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    networks:
      - booking-net
    restart: unless-stopped

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "59121:9121"
    environment:
      REDIS_ADDR: redis://redis:6379
    networks:
      - booking-net
    restart: unless-stopped
    depends_on:
      - redis

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    ports:
      - "59187:9187"
    environment:
      DATA_SOURCE_NAME: "postgresql://booking_user:booking_pass@postgres-master:5432/booking_system_auth?sslmode=disable"
    networks:
      - booking-net
    restart: unless-stopped
    depends_on:
      - postgres-master

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "59200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - booking-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    ports:
      - "55601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - booking-net

  gateway:
    build:
      context: ../gateway
      dockerfile: Dockerfile
    ports:
      - "53000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev_jwt_secret
      - JWT_REFRESH_SECRET=dev_refresh_secret
      - GRPC_AUTH_SERVICE_URL=auth-service:50051
      - GRPC_USER_SERVICE_URL=user-profile:50052
      - GRPC_EVENT_SERVICE_URL=event-management:50053
      - GRPC_BOOKING_SERVICE_URL=booking-service:50054
      - GRPC_BOOKING_WORKER_URL=booking-worker:50055
      - GRPC_PAYMENT_SERVICE_URL=payment-service:50056
      - GRPC_TICKET_SERVICE_URL=ticket-service:50057
      - GRPC_NOTIFICATION_SERVICE_URL=notification-service:50058
      - GRPC_ANALYTICS_SERVICE_URL=analytics-service:50059
      - GRPC_PRICING_SERVICE_URL=pricing-service:50060
      - GRPC_SUPPORT_SERVICE_URL=support-service:50061
      - GRPC_INVOICE_SERVICE_URL=invoice-service:50062
    depends_on:
      - redis
      - auth-service
    volumes:
      - ../gateway:/app
      - /app/node_modules
    networks:
      - booking-net
    restart: unless-stopped

  auth-service:
    build:
      context: ../auth-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - NODE_ENV=development
      - PORT=50051
      - HOST=0.0.0.0
      - DB_MASTER_HOST=postgres-master
      - DB_MASTER_PORT=5432
      - DB_MASTER_NAME=booking_system_auth
      - DB_MASTER_USER=booking_user
      - DB_MASTER_PASSWORD=booking_pass
      - DB_SLAVE_HOST=postgres-slave1
      - DB_SLAVE_PORT=5432
      - DB_SLAVE_NAME=booking_system_auth
      - DB_SLAVE_USER=booking_user
      - DB_SLAVE_PASSWORD=booking_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=dev_jwt_secret
      - JWT_REFRESH_SECRET=dev_refresh_secret
    depends_on:
      - postgres-master
      - postgres-slave1
      - redis
    volumes:
      - ../auth-service:/app
      - /app/node_modules
    networks:
      - booking-net
    restart: unless-stopped

  email-worker:
    build:
      context: ../email-worker
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "50060:50060"
    environment:
      - NODE_ENV=development
      - PORT=8080
      - GRPC_PORT=50060
      - HOST=0.0.0.0
      - DB_MASTER_HOST=postgres-main-master
      - DB_MASTER_PORT=5432
      - DB_MASTER_NAME=booking_system
      - DB_MASTER_USER=booking_user
      - DB_MASTER_PASSWORD=booking_pass
      - DB_SLAVE_HOST=postgres-main-slave1
      - DB_SLAVE_PORT=5432
      - DB_SLAVE_NAME=booking_system
      - DB_SLAVE_USER=booking_user
      - DB_SLAVE_PASSWORD=booking_pass
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKERS=kafka:9092
      - EMAIL_PROVIDER=sendgrid
      - EMAIL_API_KEY=your_sendgrid_api_key_here
      - EMAIL_FROM=noreply@booking-system.com
    depends_on:
      - postgres-main-master
      - postgres-main-slave1
      - redis
      - kafka
    volumes:
      - ../email-worker:/app
    networks:
      - booking-net
    restart: unless-stopped

volumes:
  postgres_master_data:
  postgres_slave1_data:
  postgres_slave2_data:
  postgres_data:
  postgres_main_master_data:
  postgres_main_slave1_data:
  postgres_main_slave2_data:
  redis_data:
  grafana_data:
  elasticsearch_data:
  prometheus_data:
  alertmanager_data:

networks:
  booking-net:
    driver: bridge
