global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:53000"]

  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:50051"]

  - job_name: "email-worker"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8080"]
